# Generated by Django 3.2.5 on 2021-07-07 19:07

from django.db import migrations, models
import fscohort.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('number', models.IntegerField(validators=[fscohort.models.validate_number])),
            ],
        ),
    ]
