# Generated by Django 3.2.5 on 2021-07-07 19:28

from django.db import migrations, models
import fscohort.models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[fscohort.models.validate_number]),
        ),
    ]
